---

- name: Ping
  hosts: raspberrypi
  gather_facts: false

  tasks:

    - name: Ping check
      ansible.builtin.ping:
      register: status

    - name: debug
      ansible.builtin.debug:
        msg: "{{ status }}"
